[project]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Day6"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pip = ">=25.0.1,<26"

[pypi-dependencies]
ipykernel = ">=6.29.5, <7"
numpy = ">=2.2.4, <3"
xarray = ">=2025.3.1, <2026"
h5py = ">=3.13.0, <4"
requests = ">=2.32.3, <3"
tqdm = ">=4.67.1, <5"
pandas = ">=2.2.3, <3"
netcdf4 = ">=1.7.2, <2"
pyarrow = ">=19.0.1, <20"
scipy = ">=1.15.2, <2"
xml2dict = ">=0.2.2, <0.3"
xmltodict = ">=0.14.2, <0.15"
